export const unit = {
  regiment: "3e Régiment du Matériel",
  company: "Détachement Montauban",
  sections: [
    { id: "section-1", name: "Section 1" },
    { id: "section-2", name: "Section 2" },
    { id: "section-3", name: "Section 3" },
  ],
};

export const soldiers = [
  {
    id: "s-001",
    name: "Caporal Antoine Martin",
    fullName: "Antoine Martin",
    rank: "Caporal",
    section: "Section 1",
    sectionId: "section-1",
    commandCategory: "CHEF_DE_SECTION",
    photo: "https://i.pravatar.cc/480?img=12",
  },
  {
    id: "s-002",
    name: "Soldat Lucas Bernard",
    fullName: "Lucas Bernard",
    rank: "Soldat",
    section: "Section 1",
    sectionId: "section-1",
    commandCategory: "MILITAIRE_DU_RANG",
    photo: "https://i.pravatar.cc/480?img=14",
  },
  {
    id: "s-003",
    name: "Sergent Hugo Leroy",
    fullName: "Hugo Leroy",
    rank: "Sergent",
    section: "Section 1",
    sectionId: "section-1",
    commandCategory: "SERGENT",
    photo: "https://i.pravatar.cc/480?img=16",
  },
  {
    id: "s-004",
    name: "Caporal Emma Petit",
    fullName: "Emma Petit",
    rank: "Caporal",
    section: "Section 2",
    sectionId: "section-2",
    commandCategory: "MILITAIRE_DU_RANG",
    photo: "https://i.pravatar.cc/480?img=32",
  },
  {
    id: "s-005",
    name: "Soldat Ines Dubois",
    fullName: "Ines Dubois",
    rank: "Soldat",
    section: "Section 2",
    sectionId: "section-2",
    commandCategory: "MILITAIRE_DU_RANG",
    photo: "https://i.pravatar.cc/480?img=35",
  },
  {
    id: "s-006",
    name: "Adjudant Camille Roy",
    fullName: "Camille Roy",
    rank: "Adjudant",
    section: "Section 2",
    sectionId: "section-2",
    commandCategory: "SOUS_OFFICIER_ADJOINT",
    photo: "https://i.pravatar.cc/480?img=36",
  },
  {
    id: "s-007",
    name: "Sergent Theo Mercier",
    fullName: "Theo Mercier",
    rank: "Sergent",
    section: "Section 3",
    sectionId: "section-3",
    commandCategory: "SERGENT",
    photo: "https://i.pravatar.cc/480?img=52",
  },
  {
    id: "s-008",
    name: "Soldat Nadia Moreau",
    fullName: "Nadia Moreau",
    rank: "Soldat",
    section: "Section 3",
    sectionId: "section-3",
    commandCategory: "MILITAIRE_DU_RANG",
    photo: "https://i.pravatar.cc/480?img=48",
  },
  {
    id: "s-009",
    name: "Caporal Julien Fontaine",
    fullName: "Julien Fontaine",
    rank: "Caporal",
    section: "Section 3",
    sectionId: "section-3",
    commandCategory: "MILITAIRE_DU_RANG",
    photo: "https://i.pravatar.cc/480?img=58",
  },
];
